analytics: {}
color:
  brandColors:
    - '#98B8D0'
    - '#085080'
    - '#788088'
    - '#4890C8'
    - '#70B0E0'
  brandStrength: 1
  lightness: 0.765765
  rhythmicContrast: 0.716216
  saturation: 0.484234
cta: {}
layout_spectrum: 0.817567
name: FreeScottDavis
opengraph: {}
purpose: {}
typography_spectrum: 0.806306
