typography_spectrum: 0.806306
color:
  brandColors:
    - '#98B8D0'
    - '#085080'
    - '#788088'
    - '#4890C8'
    - '#70B0E0'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.382882
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.817567
analytics:
  google: null
  facebook: null
  twitter: null
name: FreeScottDavis
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Free Scott Davis
description: An Innocent Man
purpose:
  - name: null
    item: null
    url: null
