analytics: {}
color:
  brandColors:
    - '#98B8D0'
    - '#085080'
    - '#788088'
    - '#4890C8'
    - '#70B0E0'
  brandStrength: 0.968468
  lightness: 0.504688
  rhythmicContrast: 0.700424
  saturation: 0.821359
cta: {}
layout_spectrum: 0.952702
name: FreeScottDavis
opengraph: {}
purpose: {}
typography_spectrum: 0.806306
