analytics: {}
color:
  brandColors:
    - '#98B8D0'
    - '#085080'
    - '#788088'
    - '#4890C8'
    - '#70B0E0'
  brandStrength: 0.641891
  lightness: 0.639639
  rhythmicContrast: 0.592342
  saturation: 0.382882
cta: {}
layout_spectrum: 0.817567
name: FreeScottDavis
opengraph: {}
purpose: {}
typography_spectrum: 0.806306
